spring:
    datasource:
        url: jdbc:mariadb://127.0.0.1:3306/myapp
        username: root
        password: tupsud

    jpa:
        hibernate:
            ddl-auto: update
    
       
    http:
        multipart:
            max-file-size: 3MB
            max-request-size: 20MB

desktop:
    paths:
        uploadedFiles: C:\Users\Epu\Desktop\Tarkvaratehnika-projekt\adPortal2\pildid
        
management:
       port: 9002
       security:
            enabled: false 